### ISSUE TITLE
Edit the README.md

### ISSUE THREAD

**Issue by nicolaslopezj** [jorisroling/orion-lang-nl#1]
Remember to change the README, you leaved the instructions.

**Comment by nicolaslopezj** [comment]
Just realized that you did this. 

Run:

``` sh
meteor publish --update
```

To update the readme in atmosphere without changing the version

**Comment by jorisroling** [comment]
What instruction would you like there?

Regards,

Joris

**Comment by nicolaslopezj** [comment]
No instructions, the readme you have is ok. You just need to send that to atmosphere.

**Comment by jorisroling** [comment]
Got it: done.

(I ran meteor publish --update) 

Regards,

Joris

**Comment by nicolaslopezj** [comment]
Perfect
